//! The content ids of the assets that ship with the app, computed at build time.
//!
//! Both catalogs (`src/builtins.rs` for brush shapes, `src/grounds.rs` for canvas
//! grounds) note the same catch: **an id is only knowable once the bytes have
//! arrived**, because the id is a hash of the decoded image. That is why presets
//! are seeded after startup rather than at load, and it is why a peer who saw a
//! `SetSurface` naming a ground that ships with the app had no way to tell it was
//! one — so it fetched several megabytes over the network that were already on
//! disk beside the binary.
//!
//! Hashing them here breaks that circularity: at run time the id is known, and
//! only the *bytes* still need fetching.
//!
//! **Ids only, never bytes.** Embedding the images would undo the reason they are
//! fetched at runtime in the first place — the four bundled assets are 17 MB of
//! source, and the point of `asset!` is to keep them out of the wasm binary.

use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=assets/shape");
    println!("cargo::rerun-if-changed=assets/surface");

    let mut rows = Vec::new();
    // A shape decodes as coverage and a ground as height — the one difference
    // between the two kinds, and the directory is what says which.
    for (dir, kind) in [("shape", Kind::Coverage), ("surface", Kind::Height)] {
        for entry in read_pngs(dir) {
            let bytes = std::fs::read(&entry).unwrap_or_else(|e| {
                panic!("reading bundled asset {}: {e}", entry.display());
            });
            let canonical = match kind {
                Kind::Coverage => stark_assetid::coverage(&bytes),
                Kind::Height => stark_assetid::height(&bytes),
            }
            .unwrap_or_else(|e| panic!("hashing bundled asset {}: {e}", entry.display()));
            let name = entry
                .file_name()
                .and_then(|n| n.to_str())
                .expect("asset file name is utf-8");
            rows.push(format!(
                "    (\"{dir}/{name}\", AssetId({:?})),",
                canonical.id().0
            ));
        }
    }

    let out = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("builtin_ids.rs");
    let table = format!(
        "// @generated by build.rs from assets/{{shape,surface}} — do not edit.\n\
         pub(crate) static BUILTIN_IDS: &[(&str, AssetId)] = &[\n{}\n];\n",
        rows.join("\n")
    );
    std::fs::write(&out, table).expect("writing builtin_ids.rs");
}

enum Kind {
    Coverage,
    Height,
}

/// The PNGs in `assets/<dir>`, in a stable order so the generated table does not
/// churn between builds on filesystems that enumerate differently.
fn read_pngs(dir: &str) -> Vec<std::path::PathBuf> {
    let mut found: Vec<_> = std::fs::read_dir(Path::new("assets").join(dir))
        .unwrap_or_else(|e| panic!("listing assets/{dir}: {e}"))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x.eq_ignore_ascii_case("png")))
        .collect();
    found.sort();
    found
}
