//! The content ids of the assets the app ships, computed at build time.
//!
//! An id is only knowable once the bytes have arrived, because the id *is* a hash of
//! the decoded image (§19). That circularity is why brush presets are seeded after
//! startup rather than at load, and it is why a peer who saw a `SetSubstrate` naming a
//! substrate that ships with the app had no way to tell it was one — so it pulled
//! several megabytes over the network for bytes already on disk.
//!
//! Hashing them here breaks it: at run time the id is known, and only the *bytes*
//! still need fetching. `stark-assetid` exists to make this possible — no GPU, no
//! wgpu, so a build script can compute an id.
//!
//! **Ids only, never bytes.** This crate compiles to wasm; the images are 17 MB.
//!
//! # Where the images are
//!
//! `crates/stark-dioxus-frontend/assets/`, which is a crate boundary pointing the
//! wrong way. It is deliberate and it is already documented as such (CLAUDE.md, and
//! `stark_testdata::assets`): Dioxus's `asset!` macro refuses any path outside its own
//! crate, so the web frontend cannot reference them from anywhere else, and at 17 MB
//! they are not worth a second copy.
//!
//! What this file changes is **how many places know that**. It was one build script
//! per frontend as soon as there were two frontends; it is one here, in the crate both
//! of them depend on, which is the same containment `stark-testdata` uses for the
//! same directory.

use std::path::{Path, PathBuf};

fn main() {
    let assets = assets_dir();
    let mut rows = Vec::new();
    // A shape decodes as coverage and a substrate as height — the one difference
    // between the two kinds, and the directory is what says which.
    for (dir, kind) in [("shape", Kind::Coverage), ("substrate", Kind::Height)] {
        let path = assets.join(dir);
        println!("cargo::rerun-if-changed={}", path.display());
        for entry in read_pngs(&path) {
            let bytes = std::fs::read(&entry)
                .unwrap_or_else(|e| panic!("reading shipped asset {}: {e}", entry.display()));
            let canonical = match kind {
                Kind::Coverage => stark_assetid::coverage(&bytes),
                Kind::Height => stark_assetid::height(&bytes),
            }
            .unwrap_or_else(|e| panic!("hashing shipped asset {}: {e}", entry.display()));
            let name = entry
                .file_name()
                .and_then(|n| n.to_str())
                .expect("asset file name is utf-8");
            rows.push(format!(
                "    (\"{dir}/{name}\", AssetId({:?})),",
                canonical.id().0
            ));
        }
    }
    // Sorted, so the generated table does not depend on the order a directory
    // listing happens to come back in — which differs between filesystems and would
    // make one build's table a reordering of another's for no reason.
    rows.sort();

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("shipped_ids.rs");
    let table = format!(
        "// @generated by build.rs from the shipped assets — do not edit.\n\
         pub(crate) static SHIPPED_IDS: &[(&str, AssetId)] = &[\n{}\n];\n",
        rows.join("\n")
    );
    std::fs::write(&out, table).expect("writing shipped_ids.rs");
}

/// Where the images live, relative to this crate.
fn assets_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    Path::new(&manifest).join("../stark-dioxus-frontend/assets")
}

enum Kind {
    Coverage,
    Height,
}

/// Every `.png` directly under `dir`, sorted — a missing directory is empty rather
/// than fatal, so a checkout without the images still builds the crate.
fn read_pngs(dir: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        println!("cargo::warning=no shipped assets under {}", dir.display());
        return Vec::new();
    };
    let mut out: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e.eq_ignore_ascii_case("png")))
        .collect();
    out.sort();
    out
}
