//! The host's handles on the deposited artifacts (§6.10).
//!
//! **A field rather than a lookup by name.** The entry points of an artifact are known
//! here, so a caller naming one that does not exist is a compile error rather than a
//! `None` at pipeline creation — and the variants of a shader are checked to agree
//! about them, since a `@if` that dropped an entry point would otherwise surface as a
//! missing-entry-point panic from `wgpu` in exactly one colour space.

use std::collections::BTreeMap;
use std::path::Path;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::docs::header_summary;
use crate::entries::{Axis, Entry};
use crate::link::Reflections;
use crate::reflect::Reflected;

/// The names `stark-shaders` writes by hand at its crate root. A shader mirroring onto
/// one of them would be a redefinition several hundred generated lines away from the
/// file that caused it.
const RESERVED: &[&str] = &["BindKind", "Binding", "EntryPoint", "Use", "Sample"];

/// Fail unless every item this generator puts at the crate root has a name of its own.
///
/// Three families land there — a record and an accessor per module, an enum per axis —
/// from spellings that are not distinct on their face: `a_b.wesl` and `a__b.wesl` both
/// camel-case to `AB`, and a `resid.wesl` would take the `Resid` axis's name. Asked as
/// one uniqueness question rather than as a list of the collisions someone thought of.
fn names_are_distinct(entries: &[Entry<'_>], axes: &[Axis<'_>]) {
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    let mut claim = |name: String, what: String| {
        assert!(
            !RESERVED.contains(&name.as_str()),
            "{what} is `{name}`, which `stark-shaders` declares by hand.",
        );
        if let Some(other) = seen.insert(name.clone(), what.clone()) {
            panic!("{what} and {other} are both `{name}`.");
        }
    };
    for axis in axes {
        claim(
            axis.ty.to_string(),
            format!("the `{}` axis's type", axis.feature),
        );
    }
    for entry in entries {
        let module = entry.module.path.as_str();
        claim(
            record_ident(entry).to_string(),
            format!("`{module}.wesl`'s record"),
        );
        claim(
            entry.module.rust.clone(),
            format!("`{module}.wesl`'s accessor"),
        );
    }
}

/// Generate the accessors, the records and the axis types into `dest`.
pub(crate) fn generate(
    entries: &[Entry<'_>],
    axes: &[Axis<'_>],
    pigment: bool,
    reflections: &Reflections,
    dest: &Path,
) {
    let text = accessors(entries, axes, pigment, reflections);
    std::fs::write(dest, text).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

fn accessors(
    entries: &[Entry<'_>],
    axes: &[Axis<'_>],
    pigment: bool,
    reflections: &Reflections,
) -> String {
    names_are_distinct(entries, axes);
    let types = axes.iter().map(|a| axis_type(a, pigment));
    let records = entries.iter().map(|e| record(e, reflections));
    let fns = entries.iter().map(|e| accessor(e, reflections));
    let file = syn::parse2(quote!(#(#types)* #(#records)* #(#fns)*))
        .expect("the generator emits a parseable file");
    format!(
        "// @generated by `stark-shaders-build` from the WESL sources — do not edit.\n\
         //\n\
         // One record and one accessor per module declaring an entry point, discovered\n\
         // rather than listed, documented from that module's own header. A parameter per\n\
         // axis it is linked along, whose `on` variant exists only where this build linked\n\
         // that variant. The entry points are naga's answer about the *linked* artifact,\n\
         // kept from the type check (`check.rs`, `reflect.rs`).\n\n{}",
        prettyplease::unparse(&file),
    )
}

/// The enum that chooses between one axis's two builds.
///
/// Generated for **every** declared axis, linked or not: a caller still has to name
/// the parameter, and in a build that did not link the axis the type is the one value
/// it could legally have been.
fn axis_type(axis: &Axis<'_>, pigment: bool) -> TokenStream {
    let ident = format_ident!("{}", axis.ty);
    let (off, on) = (format_ident!("{}", axis.off), format_ident!("{}", axis.on));
    let doc = format!(
        " Which of a shader's two builds a caller wants, where they differ by {}.",
        axis.what,
    );
    let doc_gate = format!(
        " The `{}` arm is generated only where this build linked that variant, so an \
         artifact it did not deposit cannot be named.",
        axis.on,
    );
    let off_doc = format!(" Linked with the `{}` feature off.", axis.feature);
    let on_doc = format!(" Linked with `{}` on.", axis.feature);
    let on_variant = axis.live(pigment).then(|| {
        quote! {
            #[doc = #on_doc]
            #on,
        }
    });
    let on_arm = axis.live(pigment).then(|| quote!(Self::#on => true,));
    let on_fn_doc = format!(
        " Whether this is the `{}` build, as the flag a host branches on.",
        axis.on,
    );
    quote! {
        #[doc = #doc]
        #[doc = ""]
        #[doc = #doc_gate]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum #ident {
            #[doc = #off_doc]
            #off,
            #on_variant
        }

        impl #ident {
            #[doc = #on_fn_doc]
            #[doc = ""]
            #[doc = " Derived rather than carried beside the variant, so a caller cannot hold"]
            #[doc = " two spellings of one choice."]
            pub const fn on(self) -> bool {
                match self {
                    Self::#off => false,
                    #on_arm
                }
            }
        }
    }
}

/// The Rust type name one shader's record takes: its module name, camel-cased.
fn record_ident(entry: &Entry<'_>) -> proc_macro2::Ident {
    let name: String = entry
        .module
        .rust
        .split('_')
        .map(|word| {
            let mut c = word.chars();
            c.next()
                .map(|f| f.to_uppercase().collect::<String>() + c.as_str())
                .unwrap_or_default()
        })
        .collect();
    format_ident!("{name}")
}

/// One shader's record type: the WGSL, and a field per entry point.
///
/// The entry points are taken from the plain build. Every variant is checked to declare
/// the same ones ([`agree`]), which is what makes one type answer for all of them.
fn record(entry: &Entry<'_>, reflections: &Reflections) -> TokenStream {
    let eps = agree(entry, reflections);
    let ident = record_ident(entry);
    let module = entry.module.path.as_str();
    let mut docs = header_summary(&entry.module.src);
    if docs.is_empty() {
        docs = vec![format!(" What `{module}.wesl` links to.")];
    }
    docs.push(String::new());
    docs.push(format!(
        " The WGSL, and one field per entry point `{module}.wesl` declares — so a \
         pipeline names an entry point at compile time rather than by string."
    ));
    let fields = eps.iter().map(|ep| {
        // The two fields this record carries besides its entry points. An entry point
        // of either name would be one field declared twice, several hundred generated
        // lines from the `.wesl` that named it.
        assert!(
            !["wgsl", "entries"].contains(&ep.name.as_str()),
            "`{module}.wesl`'s `{}` would take a field its record already has.",
            ep.name,
        );
        let field = format_ident!("{}", ep.name);
        let doc = format!(" `@{} fn {}`.", stage_word(ep.stage), ep.name);
        quote! {
            #[doc = #doc]
            pub #field: EntryPoint,
        }
    });
    quote! {
        #(#[doc = #docs])*
        #[derive(Clone, Copy, Debug)]
        pub struct #ident {
            /// The linked WGSL, for `wgpu::ShaderSource::Wgsl`.
            pub wgsl: &'static str,
            /// Every entry point below, in one slice — for a consumer asking about the
            /// *set* rather than naming a field.
            pub entries: &'static [EntryPoint],
            #(#fields)*
        }
    }
}

/// The entry points every build of `entry` agrees on — one record type answers for all
/// of a shader's variants, so a `@if` that took one away must be refused here.
fn agree<'a>(entry: &Entry<'_>, reflections: &'a Reflections) -> &'a [Reflected] {
    let builds = entry.builds();
    let shape = |artifact: &str| -> Vec<(String, naga::ShaderStage)> {
        at(reflections, artifact)
            .iter()
            .map(|e| (e.name.clone(), e.stage))
            .collect()
    };
    let first = builds[0].artifact.as_str();
    let want = shape(first);
    assert!(
        !want.is_empty(),
        "`{}.wesl` links as an artifact but declares no entry point",
        entry.module.path,
    );
    for build in &builds[1..] {
        let got = shape(&build.artifact);
        assert_eq!(
            got, want,
            "`{}` and `{first}` declare different entry points. Every variant of a \
             shader shares one record type, and a pipeline built over the variant that \
             lost one fails at `create_*_pipeline` — on a GPU, in whichever colour \
             space links it.",
            build.artifact,
        );
    }
    at(reflections, first)
}

fn at<'a>(reflections: &'a Reflections, artifact: &str) -> &'a [Reflected] {
    reflections
        .get(artifact)
        .unwrap_or_else(|| panic!("`{artifact}` was not linked"))
}

/// One entry point's value.
fn entry_point_value(ep: &Reflected) -> TokenStream {
    let name = ep.name.as_str();
    let stage = stage_path(ep.stage);
    let [x, y, z] = ep.workgroup_size.map(proc_macro2::Literal::u32_unsuffixed);
    let targets = ep
        .targets
        .iter()
        .copied()
        .map(proc_macro2::Literal::u32_unsuffixed);
    let uses = ep.uses.iter().map(|u| {
        let module = format_ident!("{}", u.module);
        let decl = format_ident!("{}", u.decl);
        let sampled = u.sampled;
        quote!(Use { decl: crate::mirror::#module::decl::#decl, sampled: #sampled })
    });
    quote! {
        EntryPoint {
            name: #name,
            stage: #stage,
            workgroup_size: [#x, #y, #z],
            targets: &[#(#targets),*],
            uses: &[#(#uses),*],
        }
    }
}

/// One artifact's whole record, as a value.
///
/// Each entry point is bound to a `const` first, so its field and its place in the
/// record's `entries` slice name one value rather than two copies of one.
fn record_value(ident: &proc_macro2::Ident, artifact: &str, eps: &[Reflected]) -> TokenStream {
    let bound: Vec<proc_macro2::Ident> = eps
        .iter()
        .map(|ep| format_ident!("{}", ep.name.to_uppercase()))
        .collect();
    let consts = eps.iter().zip(&bound).map(|(ep, name)| {
        let value = entry_point_value(ep);
        quote!(const #name: EntryPoint = #value;)
    });
    let fields = eps.iter().zip(&bound).map(|(ep, name)| {
        let field = format_ident!("{}", ep.name);
        quote!(#field: #name,)
    });
    quote! {
        {
            #(#consts)*
            #ident {
                wgsl: include_wesl!(#artifact),
                entries: &[#(#bound),*],
                #(#fields)*
            }
        }
    }
}

/// One artifact as a `static` inside its accessor, and a reference to it — a `static`
/// per build at module scope would be forty more names for nothing.
fn held(ident: &proc_macro2::Ident, artifact: &str, eps: &[Reflected]) -> TokenStream {
    let value = record_value(ident, artifact, eps);
    quote! {
        static IT: #ident = #value;
        &IT
    }
}

/// One entry point's accessor: its artifacts, chosen by its axes.
fn accessor(entry: &Entry<'_>, reflections: &Reflections) -> TokenStream {
    let name = format_ident!("{}", entry.module.rust);
    let ident = record_ident(entry);
    let params: Vec<_> = entry
        .axes
        .iter()
        .map(|a| {
            (
                format_ident!("{}", a.ty.to_lowercase()),
                format_ident!("{}", a.ty),
            )
        })
        .collect();
    let docs = doc(entry, &params);

    let builds = entry.builds();
    let body = if params.is_empty() {
        let artifact = builds[0].artifact.as_str();
        held(&ident, artifact, at(reflections, artifact))
    } else {
        let arms = builds.iter().map(|b| {
            let pats = b.on.iter().enumerate().map(|(i, &on)| {
                let ty = format_ident!("{}", entry.axes[i].ty);
                let v = format_ident!(
                    "{}",
                    if on {
                        entry.axes[i].on
                    } else {
                        entry.axes[i].off
                    }
                );
                quote!(#ty::#v)
            });
            let artifact = b.artifact.as_str();
            let pat = tuple(pats);
            let body = held(&ident, artifact, at(reflections, artifact));
            quote!(#pat => { #body })
        });
        let scrutinee = tuple(params.iter().map(|(p, _)| quote!(#p)));
        quote! {
            match #scrutinee {
                #(#arms)*
            }
        }
    };

    let args = params.iter().map(|(p, ty)| quote!(#p: #ty));
    quote! {
        #(#[doc = #docs])*
        pub fn #name(#(#args),*) -> &'static #ident {
            #body
        }
    }
}

/// `x` for one, `(x, y)` for more — a one-element tuple needs a trailing comma in both
/// the scrutinee and the pattern, and reads worse than the value it wraps.
fn tuple(parts: impl Iterator<Item = TokenStream>) -> TokenStream {
    let parts: Vec<TokenStream> = parts.collect();
    match parts.as_slice() {
        [one] => quote!(#one),
        many => quote!((#(#many),*)),
    }
}

/// The `wgpu::ShaderStages` a naga stage is, as a path. A stage a pipeline cannot be
/// built from is refused rather than mapped ([`stage_word`]).
fn stage_path(stage: naga::ShaderStage) -> TokenStream {
    let ident = format_ident!("{}", stage_word(stage).to_uppercase());
    quote!(wgpu::ShaderStages::#ident)
}

fn stage_word(stage: naga::ShaderStage) -> &'static str {
    match stage {
        naga::ShaderStage::Vertex => "vertex",
        naga::ShaderStage::Fragment => "fragment",
        naga::ShaderStage::Compute => "compute",
        other => panic!("`{other:?}` is a shader stage this mirror has no `wgpu` name for"),
    }
}

/// The accessor's documentation: the shader's own opening paragraph, then what each
/// parameter picks — the shader's words rather than a second summary (§6.10).
fn doc(entry: &Entry<'_>, params: &[(proc_macro2::Ident, proc_macro2::Ident)]) -> Vec<String> {
    let module = entry.module.path.as_str();
    let summary = header_summary(&entry.module.src);
    let mut docs = if summary.is_empty() {
        vec![format!(" The WGSL `{module}.wesl` links to.")]
    } else {
        summary
    };
    for ((param, _), axis) in params.iter().zip(&entry.axes) {
        docs.push(String::new());
        docs.push(format!(
            " `{param}` chooses which build this is — see [`{}`].",
            axis.ty,
        ));
    }
    docs.push(String::new());
    docs.push(format!(" `{module}.wesl`."));
    docs
}

/// What the generator emits today, written down so that changing it is deliberate —
/// [`crate::emit`]'s tests' argument, and testable for the same reason: this takes
/// already-parsed modules, so none of it needs a shader tree on disk.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::entries::discover;
    use crate::tree::Module;

    const RESID: Axis<'static> = Axis {
        feature: "resid",
        what: "a residual",
        ty: "Resid",
        off: "Without",
        on: "With",
        pigment_only: true,
        modules: &["stamp"],
    };

    const CEILING: Axis<'static> = Axis {
        feature: "ceiling",
        what: "a ceiling lane",
        ty: "Lane",
        off: "Plain",
        on: "Ceiling",
        pigment_only: false,
        modules: &["stamp"],
    };

    fn frag(header: &str) -> String {
        format!(
            "{header}@fragment\nfn fs_main() -> @location(0) vec4<f32> {{ return vec4<f32>(0.0); }}\n"
        )
    }

    /// Reflect each build's artifact straight from the module's own source: these
    /// probes are plain WGSL with no imports, so linking them would only exercise
    /// `wesl`.
    fn reflections(modules: &[Module], entries: &[Entry<'_>]) -> Reflections {
        let mut out = Reflections::new();
        for entry in entries {
            for build in entry.builds() {
                let (naga, info) = crate::check::typechecks(&entry.module.src, &build.artifact);
                let eps = crate::reflect::entry_points(
                    &naga,
                    &info,
                    &wesl::NoSourceMap,
                    &entry.module.path,
                    modules,
                    &build.artifact,
                );
                out.insert(build.artifact, eps);
            }
        }
        out
    }

    fn generated(modules: &[Module], axes: &[Axis<'_>], pigment: bool) -> String {
        let entries = discover(modules, axes, pigment);
        let reflections = reflections(modules, &entries);
        accessors(&entries, axes, pigment, &reflections)
    }

    fn body(out: &str, item: &str) -> String {
        let from = out
            .find(item)
            .unwrap_or_else(|| panic!("no `{item}` in:\n{out}"));
        let rest = &out[from..];
        let to = rest.find("\n}\n").expect("an item ends") + 3;
        rest[..to].to_string()
    }

    /// Two axes: a tuple match over every combination, in declaration order, each arm
    /// holding its own artifact's record.
    #[test]
    fn an_accessor_matches_on_every_combination_of_its_axes() {
        let out = generated(
            &[Module::parse("stamp", &frag(""))],
            &[RESID, CEILING],
            true,
        );
        for artifact in [
            "stamp",
            "stamp_resid",
            "stamp_ceiling",
            "stamp_resid_ceiling",
        ] {
            assert!(
                out.contains(&format!("include_wesl!(\"{artifact}\")")),
                "no `{artifact}` arm in:\n{out}"
            );
        }
        assert!(
            out.contains("pub fn stamp(resid: Resid, lane: Lane) -> &'static Stamp {"),
            "{out}"
        );
        assert!(out.contains("match (resid, lane) {"), "{out}");
        assert!(
            out.contains("(Resid::With, Lane::Ceiling) => {"),
            "the arms are still written in declaration order:\n{out}"
        );
    }

    /// The axis survives as a parameter with one value, which is what leaves the
    /// residual build unnameable rather than merely unbuilt — and no `cfg` reaches the
    /// caller.
    #[test]
    fn an_axis_this_build_does_not_link_keeps_its_parameter_and_loses_its_variant() {
        let out = generated(
            &[Module::parse("stamp", &frag(""))],
            &[RESID, CEILING],
            false,
        );
        assert_eq!(
            body(&out, "pub enum Resid"),
            "pub enum Resid {\n    /// Linked with the `resid` feature off.\n    Without,\n}\n",
        );
        // And `on` answers for the one variant there is, rather than naming the other.
        assert_eq!(
            body(&out, "pub const fn on(self) -> bool"),
            "pub const fn on(self) -> bool {\n\
             \x20       match self {\n\
             \x20           Self::Without => false,\n\
             \x20       }\n\
             \x20   }\n}\n",
        );
        assert!(out.contains("include_wesl!(\"stamp_ceiling\")"), "{out}");
        assert!(!out.contains("stamp_resid"), "{out}");
    }

    /// Both variants, so the host's flag is the enum's own answer (§6.7).
    #[test]
    fn a_linked_axis_answers_for_both_of_its_variants() {
        let out = generated(&[Module::parse("stamp", &frag(""))], &[RESID], true);
        assert!(
            out.contains("Self::Without => false,\n            Self::With => true,"),
            "{out}"
        );
    }

    /// A module the declared axes do not name takes no parameter and needs no match —
    /// the shape most of the tree has.
    #[test]
    fn a_shader_with_no_axes_takes_no_parameter() {
        let tree = [
            Module::parse("guides", &frag("")),
            Module::parse("stamp", &frag("")),
        ];
        let out = generated(&tree, &[RESID], true);
        assert_eq!(
            body(&out, "pub fn guides"),
            "pub fn guides() -> &'static Guides {\n\
             \x20   static IT: Guides = {\n\
             \x20       const FS_MAIN: EntryPoint = EntryPoint {\n\
             \x20           name: \"fs_main\",\n\
             \x20           stage: wgpu::ShaderStages::FRAGMENT,\n\
             \x20           workgroup_size: [0, 0, 0],\n\
             \x20           targets: &[0],\n\
             \x20           uses: &[],\n\
             \x20       };\n\
             \x20       Guides {\n\
             \x20           wgsl: include_wesl!(\"guides\"),\n\
             \x20           entries: &[FS_MAIN],\n\
             \x20           fs_main: FS_MAIN,\n\
             \x20       }\n\
             \x20   };\n\
             \x20   &IT\n}\n",
        );
    }

    /// The record is a field per entry point, so a caller names one at compile time —
    /// and the module's name camel-cases into the type.
    #[test]
    fn a_record_has_a_field_per_entry_point() {
        let out = generated(
            &[Module::parse(
                "mask_region",
                "@group(0) @binding(0) var mask: texture_2d<f32>;\n\
                 @vertex fn vs_main() -> @builtin(position) vec4<f32> {\n\
                 \x20 return vec4<f32>(0.0);\n}\n\
                 @fragment fn fs_main() -> @location(0) vec4<f32> {\n\
                 \x20 return textureLoad(mask, vec2<i32>(0), 0);\n}\n",
            )],
            &[],
            true,
        );
        assert_eq!(
            body(&out, "pub struct MaskRegion"),
            "pub struct MaskRegion {\n\
             \x20   /// The linked WGSL, for `wgpu::ShaderSource::Wgsl`.\n\
             \x20   pub wgsl: &'static str,\n\
             \x20   /// Every entry point below, in one slice \u{2014} for a consumer asking about the\n\
             \x20   /// *set* rather than naming a field.\n\
             \x20   pub entries: &'static [EntryPoint],\n\
             \x20   /// `@fragment fn fs_main`.\n\
             \x20   pub fs_main: EntryPoint,\n\
             \x20   /// `@vertex fn vs_main`.\n\
             \x20   pub vs_main: EntryPoint,\n}\n",
        );
        // The declaration is named through the generated mirror, module and all.
        assert!(
            out.contains("decl: crate::mirror::mask_region::decl::MASK"),
            "{out}"
        );
    }

    /// A compute entry point carries the grid it is dispatched over, and no target.
    #[test]
    fn a_compute_entry_point_carries_its_workgroup_size() {
        let out = generated(
            &[Module::parse(
                "blur",
                "@compute @workgroup_size(64, 2, 1) fn fft_both() {}\n",
            )],
            &[],
            true,
        );
        assert!(
            out.contains("stage: wgpu::ShaderStages::COMPUTE")
                && out.contains("workgroup_size: [64, 2, 1]")
                && out.contains("targets: &[]"),
            "{out}"
        );
    }

    /// Two spellings of one camel-cased name — the collision no list of reserved
    /// words would have held, since neither module's own name is taken.
    #[test]
    #[should_panic(expected = "are both `AB`")]
    fn two_modules_whose_records_share_a_name_are_refused() {
        generated(
            &[
                Module::parse("a_b", &frag("")),
                Module::parse("a__b", &frag("")),
            ],
            &[],
            true,
        );
    }

    /// A module taking an axis's type name: two enums by one name, several hundred
    /// generated lines apart.
    #[test]
    #[should_panic(expected = "are both `Resid`")]
    fn a_module_named_after_an_axis_is_refused() {
        let axis = Axis {
            modules: &["resid"],
            ..RESID
        };
        generated(&[Module::parse("resid", &frag(""))], &[axis], true);
    }

    /// And one taking a hand-written name from `stark-shaders`' own crate root.
    #[test]
    #[should_panic(expected = "which `stark-shaders` declares by hand")]
    fn a_module_named_after_a_hand_written_type_is_refused() {
        generated(&[Module::parse("binding", &frag(""))], &[], true);
    }

    /// A variant that lost an entry point would be a missing-entry-point panic from
    /// `wgpu`, in whichever colour space links it and nowhere else.
    #[test]
    #[should_panic(expected = "`stamp_ceiling` and `stamp` declare different entry points")]
    fn variants_that_disagree_about_their_entry_points_are_refused() {
        let modules = [Module::parse("stamp", &frag(""))];
        let entries = discover(&modules, &[CEILING], true);
        let mut reflections = reflections(&modules, &entries);
        reflections.insert("stamp_ceiling".to_string(), Vec::new());
        accessors(&entries, &[CEILING], true, &reflections);
    }

    /// The accessor's prose is the shader's own opening paragraph, and stops where the
    /// paragraph does.
    #[test]
    fn an_accessor_is_documented_from_its_modules_header() {
        let out = generated(
            &[Module::parse(
                "stamp",
                &frag("// Swept-segment brush rasterization (§6.2).\n//\n// The rest of it.\n\n"),
            )],
            &[CEILING],
            true,
        );
        assert!(
            out.contains("/// Swept-segment brush rasterization (§6.2).\n"),
            "{out}"
        );
        assert!(!out.contains("The rest of it"), "{out}");
        assert!(
            out.contains("/// `lane` chooses which build this is — see [`Lane`].\n"),
            "{out}"
        );
        assert!(out.contains("/// `stamp.wesl`.\n"), "{out}");
    }

    /// A shader with no header still gets a sentence, and it does not claim to have
    /// come from one.
    #[test]
    fn a_shader_with_no_header_is_documented_anyway() {
        let out = generated(&[Module::parse("blur", &frag(""))], &[], true);
        assert!(out.contains("/// The WGSL `blur.wesl` links to."), "{out}");
        assert!(out.contains("/// What `blur.wesl` links to."), "{out}");
    }
}
