//! The host's handles on the deposited artifacts (§6.10).
//!
//! One `pub fn` per entry point over `include_wesl!`, and one enum per axis whose `on`
//! variant is generated only where this build linked that variant — so `composite`
//! cannot be asked for a residual build that was never deposited.

use std::path::Path;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::docs::header_summary;
use crate::entries::{Axis, Entry};

/// Generate the accessors and the axis types into `dest`.
pub(crate) fn generate(entries: &[Entry<'_>], axes: &[Axis<'_>], pigment: bool, dest: &Path) {
    let text = accessors(entries, axes, pigment);
    std::fs::write(dest, text).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

fn accessors(entries: &[Entry<'_>], axes: &[Axis<'_>], pigment: bool) -> String {
    let types = axes.iter().map(|a| axis_type(a, pigment));
    let fns = entries.iter().map(accessor);
    let file =
        syn::parse2(quote!(#(#types)* #(#fns)*)).expect("the generator emits a parseable file");
    format!(
        "// @generated by `stark-shaders-build` from the WESL sources — do not edit.\n\
         //\n\
         // One accessor per module declaring an entry point, discovered rather than listed,\n\
         // documented from that module's own header. A parameter per axis it is linked\n\
         // along, whose `on` variant exists only where this build linked that variant.\n\n{}",
        prettyplease::unparse(&file),
    )
}

/// The enum that chooses between one axis's two builds.
///
/// Generated for **every** declared axis, linked or not: a caller still has to name
/// the parameter, and in a build that did not link the axis the type is the one value
/// it could legally have been.
fn axis_type(axis: &Axis<'_>, pigment: bool) -> TokenStream {
    let ident = format_ident!("{}", axis.ty);
    let (off, on) = (format_ident!("{}", axis.off), format_ident!("{}", axis.on));
    let doc = format!(
        " Which of a shader's two builds a caller wants, where they differ by {}.",
        axis.what,
    );
    let doc_gate = format!(
        " The `{}` arm is generated only where this build linked that variant, so an \
         artifact it did not deposit cannot be named.",
        axis.on,
    );
    let off_doc = format!(" Linked with the `{}` feature off.", axis.feature);
    let on_doc = format!(" Linked with `{}` on.", axis.feature);
    let on_variant = axis.live(pigment).then(|| {
        quote! {
            #[doc = #on_doc]
            #on,
        }
    });
    quote! {
        #[doc = #doc]
        #[doc = ""]
        #[doc = #doc_gate]
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum #ident {
            #[doc = #off_doc]
            #off,
            #on_variant
        }
    }
}

/// One entry point's accessor: its artifacts, chosen by its axes.
fn accessor(entry: &Entry<'_>) -> TokenStream {
    let name = format_ident!("{}", entry.module.rust);
    let params: Vec<_> = entry
        .axes
        .iter()
        .map(|a| {
            (
                format_ident!("{}", a.ty.to_lowercase()),
                format_ident!("{}", a.ty),
            )
        })
        .collect();
    let docs = doc(entry, &params);

    let builds = entry.builds();
    let body = if params.is_empty() {
        let artifact = builds[0].artifact.as_str();
        quote!(include_wesl!(#artifact))
    } else {
        let arms = builds.iter().map(|b| {
            let pats = b.on.iter().enumerate().map(|(i, &on)| {
                let ty = format_ident!("{}", entry.axes[i].ty);
                let v = format_ident!(
                    "{}",
                    if on {
                        entry.axes[i].on
                    } else {
                        entry.axes[i].off
                    }
                );
                quote!(#ty::#v)
            });
            let artifact = b.artifact.as_str();
            let pat = tuple(pats);
            quote!(#pat => include_wesl!(#artifact),)
        });
        let scrutinee = tuple(params.iter().map(|(p, _)| quote!(#p)));
        quote! {
            match #scrutinee {
                #(#arms)*
            }
        }
    };

    let args = params.iter().map(|(p, ty)| quote!(#p: #ty));
    quote! {
        #(#[doc = #docs])*
        pub fn #name(#(#args),*) -> &'static str {
            #body
        }
    }
}

/// `x` for one, `(x, y)` for more — a one-element tuple needs a trailing comma in both
/// the scrutinee and the pattern, and reads worse than the value it wraps.
fn tuple(parts: impl Iterator<Item = TokenStream>) -> TokenStream {
    let parts: Vec<TokenStream> = parts.collect();
    match parts.as_slice() {
        [one] => quote!(#one),
        many => quote!((#(#many),*)),
    }
}

/// The accessor's documentation: the shader's own opening paragraph, then what each
/// parameter picks.
///
/// The shader's words rather than a second summary beside them, for the reason every
/// other mirror is generated (§6.10).
fn doc(entry: &Entry<'_>, params: &[(proc_macro2::Ident, proc_macro2::Ident)]) -> Vec<String> {
    let module = entry.module.path.as_str();
    let summary = header_summary(&entry.module.src);
    let mut docs = if summary.is_empty() {
        vec![format!(" The WGSL `{module}.wesl` links to.")]
    } else {
        summary
    };
    for ((param, _), axis) in params.iter().zip(&entry.axes) {
        docs.push(String::new());
        docs.push(format!(
            " `{param}` chooses which build this is — see [`{}`].",
            axis.ty,
        ));
    }
    docs.push(String::new());
    docs.push(format!(" `{module}.wesl`."));
    docs
}

/// What the generator emits today, written down so that changing it is deliberate —
/// [`crate::emit`]'s tests' argument, and testable for the same reason: this takes
/// already-parsed modules, so none of it needs a shader tree on disk.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::entries::discover;
    use crate::tree::Module;

    const RESID: Axis<'static> = Axis {
        feature: "resid",
        what: "a residual",
        ty: "Resid",
        off: "Without",
        on: "With",
        pigment_only: true,
        modules: &["stamp"],
    };

    const CEILING: Axis<'static> = Axis {
        feature: "ceiling",
        what: "a ceiling lane",
        ty: "Lane",
        off: "Plain",
        on: "Ceiling",
        pigment_only: false,
        modules: &["stamp"],
    };

    fn frag(header: &str) -> String {
        format!(
            "{header}@fragment\nfn fs_main() -> @location(0) vec4<f32> {{ return vec4<f32>(0.0); }}\n"
        )
    }

    fn generated(modules: &[Module], axes: &[Axis<'_>], pigment: bool) -> String {
        let entries = discover(modules, axes, pigment);
        accessors(&entries, axes, pigment)
    }

    fn body(out: &str, item: &str) -> String {
        let from = out
            .find(item)
            .unwrap_or_else(|| panic!("no `{item}` in:\n{out}"));
        let rest = &out[from..];
        let to = rest.find("\n}\n").expect("an item ends") + 3;
        rest[..to].to_string()
    }

    /// Two axes: a tuple match over every combination, in declaration order.
    #[test]
    fn an_accessor_matches_on_every_combination_of_its_axes() {
        let out = generated(
            &[Module::parse("stamp", &frag(""))],
            &[RESID, CEILING],
            true,
        );
        assert_eq!(
            body(&out, "pub fn stamp"),
            "pub fn stamp(resid: Resid, lane: Lane) -> &'static str {\n\
             \x20   match (resid, lane) {\n\
             \x20       (Resid::Without, Lane::Plain) => include_wesl!(\"stamp\"),\n\
             \x20       (Resid::With, Lane::Plain) => include_wesl!(\"stamp_resid\"),\n\
             \x20       (Resid::Without, Lane::Ceiling) => include_wesl!(\"stamp_ceiling\"),\n\
             \x20       (Resid::With, Lane::Ceiling) => include_wesl!(\"stamp_resid_ceiling\"),\n\
             \x20   }\n}\n",
        );
    }

    /// The axis survives as a parameter with one value, which is what leaves the
    /// residual build unnameable rather than merely unbuilt — and no `cfg` reaches the
    /// caller.
    #[test]
    fn an_axis_this_build_does_not_link_keeps_its_parameter_and_loses_its_variant() {
        let out = generated(
            &[Module::parse("stamp", &frag(""))],
            &[RESID, CEILING],
            false,
        );
        assert_eq!(
            body(&out, "pub enum Resid"),
            "pub enum Resid {\n    /// Linked with the `resid` feature off.\n    Without,\n}\n",
        );
        assert_eq!(
            body(&out, "pub fn stamp"),
            "pub fn stamp(resid: Resid, lane: Lane) -> &'static str {\n\
             \x20   match (resid, lane) {\n\
             \x20       (Resid::Without, Lane::Plain) => include_wesl!(\"stamp\"),\n\
             \x20       (Resid::Without, Lane::Ceiling) => include_wesl!(\"stamp_ceiling\"),\n\
             \x20   }\n}\n",
        );
    }

    /// A module the declared axes do not name takes no parameter and needs no match —
    /// the shape most of the tree has.
    #[test]
    fn a_shader_with_no_axes_takes_no_parameter() {
        let tree = [
            Module::parse("guides", &frag("")),
            Module::parse("stamp", &frag("")),
        ];
        let out = generated(&tree, &[RESID], true);
        assert_eq!(
            body(&out, "pub fn guides"),
            "pub fn guides() -> &'static str {\n    include_wesl!(\"guides\")\n}\n",
        );
    }

    /// The accessor's prose is the shader's own opening paragraph, and stops where the
    /// paragraph does.
    #[test]
    fn an_accessor_is_documented_from_its_modules_header() {
        let out = generated(
            &[Module::parse(
                "stamp",
                &frag("// Swept-segment brush rasterization (§6.2).\n//\n// The rest of it.\n\n"),
            )],
            &[CEILING],
            true,
        );
        assert!(
            out.contains("/// Swept-segment brush rasterization (§6.2).\n"),
            "{out}"
        );
        assert!(!out.contains("The rest of it"), "{out}");
        assert!(
            out.contains("/// `lane` chooses which build this is — see [`Lane`].\n"),
            "{out}"
        );
        assert!(out.contains("/// `stamp.wesl`.\n"), "{out}");
    }

    /// A shader with no header still gets a sentence, and it does not claim to have
    /// come from one.
    #[test]
    fn a_shader_with_no_header_is_documented_anyway() {
        let out = generated(&[Module::parse("blur", &frag(""))], &[], true);
        assert!(out.contains("/// The WGSL `blur.wesl` links to."), "{out}");
    }
}
